/controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: null
    joint_state_controller:
      type: joint_state_controller/JointStateController
    panda_arm_controller:
      joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      publish_rate: 50
      type: joint_trajectory_controller/JointTrajectoryController
      write_op_modes:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    panda_handleft_controller:
      type: position_controllers/GripperActionController
    panda_handright_controller:
      type: position_controllers/GripperActionController
    update_rate: 100
    use_sim_time: false
